# Generated by Django 2.2.5 on 2019-09-29 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
