# Generated by Django 2.2.5 on 2019-09-30 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='speciality',
        ),
        migrations.RemoveField(
            model_name='speciality',
            name='subject',
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.Subject'),
        ),
    ]
