# Generated by Django 2.2.5 on 2019-09-30 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191001_0306'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Speciality',
        ),
    ]
