# Generated by Django 2.2.5 on 2019-10-01 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191002_0200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='user',
            new_name='author',
        ),
    ]
