# Generated by Django 2.2.5 on 2019-10-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20191002_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='source_link',
            field=models.CharField(default='No Source', max_length=100),
        ),
    ]
