# Generated by Django 2.2.5 on 2019-10-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20191002_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
