# Generated by Django 2.2.5 on 2019-10-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20191002_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='subject',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
