# Generated by Django 2.2.5 on 2019-10-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20191002_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
