# Generated by Django 2.2.5 on 2019-10-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20191002_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=models.SlugField(),
        ),
    ]
