# Generated by Django 2.2.5 on 2019-10-02 13:56

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20191002_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='slug',
        ),
        migrations.AddField(
            model_name='course',
            name='slug_url',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='title'),
        ),
        migrations.AddField(
            model_name='subject',
            name='slug_url',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='title'),
        ),
    ]
