# Generated by Django 2.2.5 on 2019-10-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20191002_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='source_link',
            field=models.TextField(default='No Source'),
        ),
    ]
