# Generated by Django 2.2.5 on 2019-10-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20191003_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursevideo',
            name='link',
            field=models.CharField(max_length=11),
        ),
    ]
