# Generated by Django 2.2.5 on 2019-10-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20191003_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursevideo',
            name='teacher',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
