# Generated by Django 2.2.5 on 2019-10-07 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20191006_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='slug',
        ),
        migrations.AddField(
            model_name='subject',
            name='slug',
            field=models.SlugField(default=123),
            preserve_default=False,
        ),
    ]
