# Generated by Django 2.2.5 on 2019-09-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='isAuthor',
            field=models.BooleanField(null=True),
        ),
    ]
