# Generated by Django 2.2.5 on 2019-10-01 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190930_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='isAuthor',
            new_name='is_author',
        ),
    ]
