# Generated by Django 2.2.5 on 2019-10-16 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20191002_0310'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
