# Generated by Django 2.2.5 on 2019-10-18 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_delete_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_author',
        ),
    ]
